// Copyright 2012 Google Inc. All Rights Reserved.
// Author: sreeni@google.com (Sreeni Viswanadha)

/*
 * Copyright (c) 2006, Sun Microsystems, Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted
 * provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this list of conditions
 * and the following disclaimer. * Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the documentation and/or other
 * materials provided with the distribution. * Neither the name of the Sun Microsystems, Inc. nor
 * the names of its contributors may be used to endorse or promote products derived from this
 * software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
 * WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package org.javacc.generator.cpp;

import org.fastcc.utils.DigestOptions;
import org.fastcc.utils.DigestWriter;
import org.fastcc.utils.Template;
import org.fastcc.utils.Version;
import org.javacc.JavaCC;
import org.javacc.JavaCCRequest;
import org.javacc.generator.LexerData;
import org.javacc.generator.OtherFilesGenerator;
import org.javacc.parser.JavaCCErrors;
import org.javacc.parser.Options;
import org.javacc.parser.ParseException;
import org.javacc.parser.RStringLiteral;
import org.javacc.parser.RegExprSpec;
import org.javacc.parser.RegularExpression;
import org.javacc.parser.TokenProduction;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

/**
 * Generates the Constants file.
 */
public class CppOtherFilesGenerator implements OtherFilesGenerator {

  @Override
  public final void start(LexerData data, JavaCCRequest request) throws ParseException {
    if (JavaCCErrors.hasError()) {
      throw new ParseException();
    }

    CppOtherFilesGenerator.gen_JavaCCDefs();
    CppOtherFilesGenerator.gen_CharStream();
    CppOtherFilesGenerator.gen_Token(); // TODO(theov): issued twice??
    CppOtherFilesGenerator.gen_TokenManager();
    CppOtherFilesGenerator.gen_TokenMgrError();
    CppOtherFilesGenerator.gen_ParseException();
    CppOtherFilesGenerator.gen_ErrorHandler();

    try {
      CppOtherFilesGenerator.ostr = new PrintWriter(new BufferedWriter(
          new FileWriter(new File(Options.getOutputDirectory(), request.getParserName() + "Constants.h")), 8192));
    } catch (IOException e) {
      JavaCCErrors.semantic_error("Could not open file " + request.getParserName() + "Constants.h for writing.");
      throw new Error();
    }

    CppOtherFilesGenerator.ostr.println("");
    CppOtherFilesGenerator.ostr.println("/**");
    CppOtherFilesGenerator.ostr.println(" * Token literal values and constants.");
    CppOtherFilesGenerator.ostr.println(" * Generated by org.javacc.parser.OtherFilesGenCPP#start()");
    CppOtherFilesGenerator.ostr.println(" */");

    String define = ("JAVACC_" + request.getParserName() + "Constants_h").toUpperCase();
    CppOtherFilesGenerator.ostr.println("#ifndef " + define);
    CppOtherFilesGenerator.ostr.println("#define " + define);
    CppOtherFilesGenerator.ostr.println("");
    CppOtherFilesGenerator.ostr.println("#include \"JavaCC.h\"");
    CppOtherFilesGenerator.ostr.println("");
    if (Options.stringValue(JavaCC.JJPARSER_CPP_NAMESPACE).length() > 0) {
      CppOtherFilesGenerator.ostr.println("namespace " + Options.stringValue(JavaCC.JJPARSER_CPP_NAMESPACE) + " {");
    }

    String constPrefix = "const";
    CppOtherFilesGenerator.ostr.println("  /** End of File. */");
    CppOtherFilesGenerator.ostr.println(constPrefix + "  int _EOF = 0;");
    for (RegularExpression re : request.getOrderedsTokens()) {
      CppOtherFilesGenerator.ostr.println("  /** RegularExpression Id. */");
      CppOtherFilesGenerator.ostr.println(constPrefix + "  int " + re.label + " = " + re.ordinal + ";");
    }
    CppOtherFilesGenerator.ostr.println("");

    for (int i = 0; i < data.getStateCount(); i++) {
      CppOtherFilesGenerator.ostr.println("  /** Lexical state. */");
      CppOtherFilesGenerator.ostr.println(constPrefix + "  int " + data.getStateName(i) + " = " + i + ";");
    }
    CppOtherFilesGenerator.ostr.println("");
    CppOtherFilesGenerator.ostr.println("  /** Literal token image. */");
    int cnt = 0;
    CppOtherFilesGenerator.ostr.println("  static const JJChar tokenImage_" + cnt + "[] = ");
    CppOtherFilesGenerator.printCharArray(CppOtherFilesGenerator.ostr, "<EOF>");
    CppOtherFilesGenerator.ostr.println(";");

    for (TokenProduction tp : request.getTokenProductions()) {
      List<RegExprSpec> respecs = tp.respecs;
      for (RegExprSpec res : respecs) {
        RegularExpression re = res.rexp;
        CppOtherFilesGenerator.ostr.println("  static const JJChar tokenImage_" + ++cnt + "[] = ");
        if (re instanceof RStringLiteral) {
          CppOtherFilesGenerator.printCharArray(CppOtherFilesGenerator.ostr, ((RStringLiteral) re).image);
        } else if (!re.label.equals("")) {
          CppOtherFilesGenerator.printCharArray(CppOtherFilesGenerator.ostr, "<" + re.label + ">");
        } else {
          if (re.tpContext.kind == TokenProduction.TOKEN) {
            JavaCCErrors.warning(re, "Consider giving this non-string token a label for better error reporting.");
          }
          CppOtherFilesGenerator.printCharArray(CppOtherFilesGenerator.ostr, "<token of kind " + re.ordinal + ">");
        }
        CppOtherFilesGenerator.ostr.println(";");
      }
    }

    CppOtherFilesGenerator.ostr.println("  static const JJChar* const tokenImages[] = {");
    for (int i = 0; i <= cnt; i++) {
      CppOtherFilesGenerator.ostr.println("tokenImage_" + i + ", ");
    }
    CppOtherFilesGenerator.ostr.println("  };");


    CppOtherFilesGenerator.ostr.println("  /** Literal token label. */");
    cnt = 0;
    CppOtherFilesGenerator.ostr.println("  static const JJChar tokenLabel_" + cnt + "[] = ");
    CppOtherFilesGenerator.printCharArray(CppOtherFilesGenerator.ostr, "<EOF>");
    CppOtherFilesGenerator.ostr.println(";");

    for (TokenProduction tp : request.getTokenProductions()) {
      List<RegExprSpec> respecs = tp.respecs;
      for (RegExprSpec res : respecs) {
        RegularExpression re = res.rexp;
        CppOtherFilesGenerator.ostr.println("  static const JJChar tokenLabel_" + ++cnt + "[] = ");
        if (re instanceof RStringLiteral) {
          CppOtherFilesGenerator.printCharArray(CppOtherFilesGenerator.ostr, "<" + ((RStringLiteral) re).label + ">");
        } else if (!re.label.equals("")) {
          CppOtherFilesGenerator.printCharArray(CppOtherFilesGenerator.ostr, "<" + re.label + ">");
        } else {
          if (re.tpContext.kind == TokenProduction.TOKEN) {
            JavaCCErrors.warning(re, "Consider giving this non-string token a label for better error reporting.");
          }
          CppOtherFilesGenerator.printCharArray(CppOtherFilesGenerator.ostr, "<token of kind " + re.ordinal + ">");
        }
        CppOtherFilesGenerator.ostr.println(";");
      }
    }

    CppOtherFilesGenerator.ostr.println("  static const JJChar* const tokenLabels[] = {");
    for (int i = 0; i <= cnt; i++) {
      CppOtherFilesGenerator.ostr.println("tokenLabel_" + i + ", ");
    }
    CppOtherFilesGenerator.ostr.println("  };");
    CppOtherFilesGenerator.ostr.println();

    CppOtherFilesGenerator.ostr.println("");
    if (Options.stringValue(JavaCC.JJPARSER_CPP_NAMESPACE).length() > 0) {
      CppOtherFilesGenerator.ostr.println("}");
    }
    CppOtherFilesGenerator.ostr.println("#endif");
    CppOtherFilesGenerator.ostr.close();

  }

  // Used by the CPP code generatror
  static void printCharArray(java.io.PrintWriter ostr, String s) {
    ostr.print("{");
    for (int i = 0; i < s.length(); i++) {
      ostr.print("0x" + Integer.toHexString(s.charAt(i)) + ", ");
    }
    ostr.print("0}");
  }

  static private java.io.PrintWriter ostr;

  private static void gen_CharStream() {
    CppOtherFilesGenerator.genFile("CharStream.h", JavaCC.VERSION);
    CppOtherFilesGenerator.genFile("DefaultCharStream.h", JavaCC.VERSION);
    CppOtherFilesGenerator.genFile("DefaultCharStream.cc", JavaCC.VERSION);
  }

  private static void gen_ParseException() {
    CppOtherFilesGenerator.genFile("ParseException.h", JavaCC.VERSION);
    CppOtherFilesGenerator.genFile("ParseException.cc", JavaCC.VERSION);
    CppOtherFilesGenerator.genFile("ParserErrorHandler.h", JavaCC.VERSION);
    CppOtherFilesGenerator.genFile("DefaultParserErrorHandler.h", JavaCC.VERSION);
    CppOtherFilesGenerator.genFile("DefaultParserErrorHandler.cc", JavaCC.VERSION);
  }

  private static void gen_TokenMgrError() {
    CppOtherFilesGenerator.genFile("TokenManagerError.h", JavaCC.VERSION);
    CppOtherFilesGenerator.genFile("TokenManagerError.cc", JavaCC.VERSION);
    CppOtherFilesGenerator.genFile("TokenManagerErrorHandler.h", JavaCC.VERSION);
  }

  private static void gen_Token() {
    CppOtherFilesGenerator.genFile("Token.h", JavaCC.VERSION);
    CppOtherFilesGenerator.genFile("Token.cc", JavaCC.VERSION);
  }

  private static void gen_TokenManager() {
    CppOtherFilesGenerator.genFile("TokenManager.h", JavaCC.VERSION);
  }

  private static void gen_JavaCCDefs() {
    CppOtherFilesGenerator.genFile("JavaCC.h", JavaCC.VERSION);
  }

  private static void gen_ErrorHandler() {
    CppOtherFilesGenerator.genFile("DefaultTokenManagerErrorHandler.h", JavaCC.VERSION);
    CppOtherFilesGenerator.genFile("DefaultTokenManagerErrorHandler.cc", JavaCC.VERSION);
  }

  private static void genFile(String name, Version version) {
    File file = new File(Options.getOutputDirectory(), name);
    try (DigestWriter writer = DigestWriter.create(file, version, DigestOptions.get())) {
      Template.of("/templates/cpp/" + name + ".template", writer.options()).write(writer);
    } catch (IOException e) {
      System.err.println("Failed to create file: " + file + e);
      JavaCCErrors.semantic_error("Could not open file: " + file + " for writing.");
      throw new Error();
    }
  }
}
