/*
 * Copyright (c) 2006, Sun Microsystems, Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted
 * provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this list of conditions
 * and the following disclaimer. * Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the documentation and/or other
 * materials provided with the distribution. * Neither the name of the Sun Microsystems, Inc. nor
 * the names of its contributors may be used to endorse or promote products derived from this
 * software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
 * WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package org.javacc.generator;

import org.fastcc.utils.Encoding;
import org.javacc.parser.JavaCCParserConstants;
import org.javacc.parser.Token;

import java.util.List;

/**
 * This package contains data created as a result of parsing and semanticizing a JavaCC input file.
 * This data is what is used by the back-ends of JavaCC as well as any other back-end of JavaCC
 * related tools such as JJTree.
 */
public class JavaCCToken {

  protected static int cline;
  protected static int ccol;

  public static void reset() {
    JavaCCToken.cline = 0;
    JavaCCToken.ccol = 0;
  }

  public static void setRow() {
    JavaCCToken.cline--;
  }

  public static void setColumn() {
    JavaCCToken.ccol = 1;
  }

  public static void set(Token token) {
    JavaCCToken.cline = token.beginLine;
    JavaCCToken.ccol = token.beginColumn;
  }

  /**
   * Returns the identifying string for the file name, given a set of tool names that are used to
   * generate it.
   */
  public static String getIdString(List<String> toolNames) {
    String toolNamePrefix = "Generated By:";
    int i = 0;
    for (i = 0; i < (toolNames.size() - 1); i++) {
      toolNamePrefix += toolNames.get(i) + "&";
    }
    toolNamePrefix += toolNames.get(i) + ":";

    if (toolNamePrefix.length() > 200) {
      System.out.println("Tool names too long.");
      throw new Error();
    }
    return toolNamePrefix + " Do not edit this line. ";
  }

  // TODO from UCDetector: Change visibility of Method "JavaCCToken.printTokenSetup(Token)" to
  // private
  public static void printTokenSetup(Token t) { // NO_UCD (use private)
    Token tt = t;
    while (tt.specialToken != null) {
      tt = tt.specialToken;
    }
    JavaCCToken.cline = tt.beginLine;
    JavaCCToken.ccol = tt.beginColumn;
  }

  public static String printTokenOnly(Token t) {
    String retval = "";
    for (; JavaCCToken.cline < t.beginLine; JavaCCToken.cline++) {
      retval += "\n";
      JavaCCToken.ccol = 1;
    }
    for (; JavaCCToken.ccol < t.beginColumn; JavaCCToken.ccol++) {
      retval += " ";
    }
    if ((t.kind == JavaCCParserConstants.STRING_LITERAL) || (t.kind == JavaCCParserConstants.CHARACTER_LITERAL)) {
      retval += Encoding.escapeUnicode(t.image);
    } else {
      retval += t.image;
    }
    JavaCCToken.cline = t.endLine;
    JavaCCToken.ccol = t.endColumn + 1;
    char last = t.image.charAt(t.image.length() - 1);
    if ((last == '\n') || (last == '\r')) {
      JavaCCToken.cline++;
      JavaCCToken.ccol = 1;
    }
    return retval;
  }
}
